@startuml

start
:Left Menu Opened.;
        if(User clicked anywhere?) then(yes)
            if("User List" clicked?) then (yes)
                :User navigated to User List page.;
            else
                if("Librarian List" clicked?) then (yes)
                    :User navigated to Librarian List page.;
                    
                else
                    if("Book List" clicked?) then (yes)
                        :User navigated to Boook List page .;
                        
                    else
                        if ("Software List" clicked?) then (yes)
                            :User navigated to Software List page ;
                        else (no)
                            if ("Receipts Managements" clicked?) then (yes)
                                :User navigated to Receipts Management page ;
                            else (no)
                                if ("Room Managements"?) then (yes)
                                    :User navigated to Room List Page ;  
                                else (no)
                                    if (Logout?) then (yes)
                                        :JWT killed then sessiond ends.;
                                        :Navigate to onboarding page;
                                    else (no)
                                        if(Any point out of menu clicked?) then (yes)
                                            :Menu closed;
                                        else
                                            :Point where on the menu but not on menu element clicked.
                                            :Stay on menu;
                                        endif  
                                    endif
                                endif
                            endif
                        endif
                    endif
                endif
            endif
        else
            :Stay on menu;
        endif
stop

@enduml