@startuml
actor "Librarian" as Librarian
participant "Reciept Management Page" as Page
participant "Approval Interface" as Interface
participant "Receipts Controller" as Controller
database "Database" as DB

Librarian -> Page: Requests to view unapproved receipts
activate Page
activate Interface
Page -> Interface: See unapproved receipts
deactivate Page

Interface -> Controller: Gets list of unapproved receipts
activate Controller

Controller -> DB: Queries unapproved receipts
activate DB
DB --> Controller:  list of unapproved receipts
deactivate DB

Controller --> Interface:  list to Librarian
deactivate Controller

Librarian -> Interface: Chooses receipt and enters balance to approve
activate Interface

Interface -> Controller: Sends approval and balance update
activate Controller

Controller -> DB: Updates receipt status to "Approved" and adds balance
activate DB
DB --> Controller: Response of update confirmation
deactivate DB

Controller --> Interface: Response of successful approval
deactivate Controller

Interface --> Page:  approval confirmation
deactivate Interface
@enduml
