@startuml
actor "Registered User" as User
participant "Book Collection Page" as Page
participant "Book Details Page" as Details
database "Database" as DB

User -> Page: Visits Collection Page
activate Page

Page -> DB: Get list of books
activate DB
DB --> Page:  list of books
deactivate DB
Page -> Page: Displays list of books
User -> Page: Browses books from list
opt if user clicks any Book
    activate Details
    deactivate Page
    Page -> Details:Redirect book details page
    Details -> Details:Display details of selected book
end
@enduml
