@startuml
actor "Registered User" as User
participant "Homepage" as Home
participant "Reservation Page" as Reservation
participant "Room List" as List
participant "Controller" as Controller
database "Database" as DB

User -> Home: Navigate to homepage
activate Home

Home -> Reservation: Click the “Room Reservation” button
deactivate Home
activate Reservation

Reservation -> List: Requests list of rooms
deactivate Reservation
activate List
List -> Controller: Request list of rooms
activate Controller

Controller -> DB: Retrieve rooms with pictures
activate DB
DB --> Controller:  list of rooms
deactivate DB

Controller --> List:  list of rooms and pictures
deactivate Controller
List -> List: Display room list

opt If user selects any room
    activate Reservation
    User -> Reservation: Select a room to see slots
    List --> Reservation:  selected room
    deactivate List
    Reservation -> Controller: Request queries for slots
    activate Controller
    Controller -> DB: Querie available slots for room
    activate DB
    DB --> Controller:  available slots
    deactivate DB
    Controller --> Reservation:  available slots
    deactivate Controller
    Reservation -> Reservation: Show available slots on the page
else
    Reservation -> Home: Return homepage
    deactivate Reservation

    opt If user wanna select time slot
        User -> Reservation: Make reservation for available slot
        activate Reservation
        Reservation -> Controller: Request for booking
        activate Controller
        Controller -> DB: Book selected slot
        activate DB
        DB --> Controller: Response of Confirmation for reservation
        deactivate DB
        Controller --> Reservation: Response of Confirmation message
        deactivate Controller
        Reservation --> User: Indicate successful booking
    else
        Reservation -> Home: Return homepage
        deactivate Reservation
    end
end
@enduml
