@startuml
actor  User as User
participant "Homepage" as Home
participant "User Detail Page" as Page
participant "Controller" as Controller
database "Database" as DB

User -> Home: Enter homepage
activate Home
deactivate Home

User -> Page: Click 'Three Dot Icon'
activate Page

Page -> Controller: get user details
activate Controller

Controller -> DB: Fetche User Details
activate DB
DB --> Controller:  User Details
deactivate DB
Controller --> Page:  User Detail Object
deactivate Controller
Page -> Page:Display User Detail On The Screen

deactivate Page
@enduml