@startuml
actor user as User
participant OnboardingPage as OnboardingPage
participant RegistrationPage as RegistrationPage
participant LoginPage as LoginPage
participant HomePage as Home
participant EmailService as EmailS
participant Controller as UserEntity
participant Validation as Validation
database Database

activate OnboardingPage
User -> OnboardingPage: Logs into the application
activate RegistrationPage
alt If user clicks registration button
    OnboardingPage -> RegistrationPage: Click on register button
    deactivate OnboardingPage
    RegistrationPage -> UserEntity: Fill out the user form
    activate UserEntity

    UserEntity -> Validation: Validating user information 
    activate Validation
    Validation -> Database: Check if the user exists
    activate Database
    Database --> Validation:  user information
    deactivate Database

    Validation -> Validation : Check Email format

    deactivate Validation

    alt Email format is correct
        UserEntity -> Database: Send Confirmation Code
        activate Database
        Database --> UserEntity:  Confirmation Code
        deactivate Database
        activate EmailS
        UserEntity --> EmailS:  Confirmation message 
        deactivate EmailS
        
        UserEntity --> RegistrationPage:  Json Web Token
        RegistrationPage --> User:  Json Web Token
        RegistrationPage -> RegistrationPage: Display confirmation code field
        User -> RegistrationPage: Enter Confirmation code
        RegistrationPage -> UserEntity: Send the confirmation code
        UserEntity -> Database: Update user status with confirmed status.
        activate Database
        Database --> UserEntity:  Success
        deactivate Database
        UserEntity --> RegistrationPage:  Registration process
        RegistrationPage -> Home: Navigate to HomePage
    else Email format is incorrect
        UserEntity --> RegistrationPage:  Error message
    end
    deactivate UserEntity
    deactivate RegistrationPage
else if user clicks login button
    OnboardingPage -> LoginPage: Click on login button
    activate OnboardingPage
    deactivate OnboardingPage
    activate LoginPage
    LoginPage -> UserEntity: Send user information to the backend
    activate UserEntity
    UserEntity -> Database: Check user information
    activate Database
    Database --> UserEntity:  validation
    deactivate Database
    alt Information is correct
        UserEntity --> LoginPage:  Json Web Token
        LoginPage --> User:  Json Web Token
        LoginPage -> Home: Navigate to HomePage
    else Information is incorrect
        UserEntity --> LoginPage:  Error message 
    end
    deactivate UserEntity
    deactivate LoginPage
end
@enduml
