@startuml SearchBookForLibrarian
actor Librarian
participant HomePage as HomePage
participant SearchPage as SearchPage
participant DetailsPage as DetailsPage
participant Controller as Controller
database Database

Librarian-> HomePage: Enter HomePage
activate HomePage

HomePage -> SearchPage: Navigate to SearchPage by Clicking on Search Icon
deactivate HomePage
activate SearchPage

SearchPage -> Controller: Send Specification Form
activate Controller

Controller -> Database: Retrieve Search Results with Specifications
activate Database

Database --> Controller: Return Search Results
deactivate Database

Controller --> SearchPage: Send Search Results
deactivate Controller
SearchPage -> SearchPage: Display Search Results

opt Delete Book
    Librarian -> SearchPage: Select a Book to Delete
    SearchPage -> Controller: Send BookID to Delete Book
    activate Controller

    Controller -> Database: Send BookID to Delete Book
    activate Database

    Database --> Controller: Return Deletion Confirmation
    deactivate Database

    Controller --> SearchPage: Return Deletion Confirmation
    deactivate Controller
    SearchPage -> SearchPage: Display Deletion Confirmation
end

opt Update Book
    Librarian -> SearchPage: Select a Book to Update
    
    SearchPage -> DetailsPage: Send Book Details to Form
    activate DetailsPage
    Librarian -> DetailsPage: Edit the Details on Form
    
    DetailsPage -> Controller: Send the Updated Form
    deactivate DetailsPage
    activate Controller
    
    Controller -> Database: Update Book
    activate Database

    Database --> Controller: Return Book Updated Successfully
    deactivate Database

    Controller --> SearchPage: Send Update Confirmation
    deactivate Controller
    SearchPage -> SearchPage: Display Update Confirmation
end

deactivate SearchPage
@enduml

