@startuml SearchBookForLibrarian
actor Librarian
participant BookListPage as SearchPage
participant DetailsPage as DetailsPage
participant Controller as Controller
database Database

Librarian -> SearchPage: Navigate to BookListPage from left menu
activate SearchPage

SearchPage -> Controller: Send Specification Form
activate Controller

Controller -> Database: Retrieve Search Results with Specifications
activate Database

Database --> Controller:  Search Results
deactivate Database

Controller --> SearchPage:  Search Results
deactivate Controller
SearchPage -> SearchPage: Display Search Results

opt Delete Book
    Librarian -> SearchPage: Select a Book to Delete
    SearchPage -> Controller: Send BookID to Delete Book
    activate Controller

    Controller -> Database: Send BookID to Delete Book
    activate Database

    Database --> Controller: Response of Deletion Confirmation
    deactivate Database

    Controller --> SearchPage: Response of Deletion Confirmation
    deactivate Controller
    SearchPage -> SearchPage: Display Deletion Confirmation
end

opt Update Book
    Librarian -> SearchPage: Select a Book to Update
    
    SearchPage -> DetailsPage: Send Book Details to Form
    activate DetailsPage
    Librarian -> DetailsPage: Edit the Details on Form
    
    DetailsPage -> Controller: Send the Updated Form
    deactivate DetailsPage
    activate Controller
    
    Controller -> Database: Update Book
    activate Database

    Database --> Controller: Response of Book Updated Successfully
    deactivate Database

    Controller --> SearchPage:  Update Confirmation
    deactivate Controller
    SearchPage -> SearchPage: Display Update Confirmation
end

deactivate SearchPage
@enduml

