@startuml
actor "Librarian" as Librarian
participant "HomePage" as Home
participant "Book Page" as Page
participant "Controller" as Controller
database "Database" as LendingDB

Librarian -> Home: Click on book page button
activate Home
Home -> Page: Requests list of borrowed books
deactivate Home
activate Page

Page -> Controller: Gets borrowed books
activate Controller

Controller -> LendingDB: Retrieves list of borrowed books
activate LendingDB
LendingDB --> Controller: List of borrowed books
deactivate LendingDB

Controller --> Page: Shows list to Librarian
deactivate Controller

Librarian -> Page: Chooses a book to take back
activate Page

Page -> Controller: Sends book return request
activate Controller

Controller -> LendingDB: Records book return
activate LendingDB
LendingDB --> Controller: Confirmation of book return
deactivate LendingDB

Controller --> Page: Confirms book taken back
deactivate Controller

Page --> Page: Display confirmation
deactivate Page
@enduml
