@startuml
actor "Librarian" as Librarian
participant "Book Page" as Page
participant "Controller" as Controller
database "Database" as LendingDB

Librarian -> Page: Request list of borrowed books
activate Page

Page -> Controller: Get borrowed books
activate Controller

Controller -> LendingDB: Retrieve list of borrowed books
activate LendingDB
LendingDB --> Controller: List of borrowed books
deactivate LendingDB

Controller --> Page:  list 
deactivate Controller

Librarian -> Page: Choose a book to take back
activate Page

Page -> Controller: Send book return request
activate Controller

Controller -> LendingDB: Record book return
activate LendingDB
LendingDB --> Controller: Response of book return
deactivate LendingDB

Controller --> Page: Confirm book taken back
deactivate Controller

Page -> Page: Display confirmation
deactivate Page
@enduml
