@startuml
actor "Registered User" as User
participant "Homepage" as Home
participant "My Books Section" as MyBooks
participant " Controller" as Controller
database " Database" as DB

activate Home
User -> Home: Click the "My Books" button
Home -> MyBooks: Navigate the “My Books” Page 
deactivate Home
activate MyBooks


MyBooks -> Controller: Request borrowed books
activate Controller

Controller -> DB: Retrieve user's borrowed books
activate DB
DB --> Controller:  borrowed books list
deactivate DB

Controller --> MyBooks:  borrowed books data
deactivate Controller

MyBooks -> MyBooks: Display borrowed books
deactivate MyBooks
@enduml
