name: Build & Test & Report & Deploy

on:
  push:
    branches: [ "main" ]
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.ADDRESS}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          script: |
            cd /home/ubuntu/repo/mlm
            git pull
            chmod +x gradlew
            ./gradlew clean    
            ./gradlew build -x test 
      - name: Run Tests
        id: run_tests
        uses: appleboy/ssh-action@v1.0.3
        continue-on-error: true
        with:
          host: ${{secrets.ADDRESS}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          script: |
            cd /home/ubuntu/repo/mlm
            ./gradlew test
      - name: Publish Tests Report
        uses: appleboy/ssh-action@v1.0.3
        if: always()
        with:
          host: ${{secrets.ADDRESS}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          script: |
            cd /home/ubuntu/repo/mlm
            currentdate=$(date +"%d%m%Y-%H%M")
            originForGradleReport="/home/ubuntu/repo/mlm/build/reports/tests/test"
            originForJacocoReport="/home/ubuntu/repo/mlm/build/reports/jacoco"
            destination="/var/www/html/reports/$currentdate"
            mkdir "$destination/"
            cp -r "$originForGradleReport" "$destination"
            cp -r "$originForJacocoReport" "$destination"
            systemctl restart nginx
      - name: Exit if there is/are failed test/s
        if: steps.run_tests.outcome != 'success'
        run: exit 1
      - name: Check Code Coverage
        id: coverage_check
        uses: appleboy/ssh-action@v1.0.3
        if: ${{ steps.run_tests.outcome == 'success' }}
        with:
          host: ${{secrets.ADDRESS}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          script: |
            cd /home/ubuntu/repo/mlm
            ./gradlew jacocoTestCoverageVerification
      - name: Exit if coverage is less than criteria
        if: steps.coverage_check.outcome != 'success'
        run: exit 1
      - name: Start MLM Server
        if: steps.coverage_check.outcome == 'success'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.ADDRESS}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          script: |
            cd /home/ubuntu/repo/mlm
            ./gradlew bootJar
            cp /home/ubuntu/repo/mlm/build/libs/mlm-1.3.0.jar /home/ubuntu/jar/
            cd /home/ubuntu/jar/
            rm app.jar
            mv mlm-1.3.0.jar app.jar
            systemctl stop app
            systemctl daemon-reload
            systemctl start app    
