name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
    

jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:
      - name: Connect to server and Pull the MLM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.ADDRESS}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          script: |
            cd /home/ubuntu/repo/mlm
            git pull
      - name: Build and Package
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.ADDRESS}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          script: |
            cd /home/ubuntu/repo/mlm
            gradle clean    
            gradle build
            gradle bootJar
            cp /home/ubuntu/repo/mlm/build/libs/mlm-1.3.0.jar /home/ubuntu/jar/
            cd /home/ubuntu/jar/
            rm app.jar
            mv mlm-1.3.0.jar app.jar
            systemctl stop app
            
