name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
    

jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.ADDRESS}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          script: |
            cd /home
            mkdir test
