name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.ADDRESS}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          script: |
            cd /home/ubuntu/repo/mlm
            git pull
            chmod +x gradlew
            ./gradlew clean    
            ./gradlew build
      - name: Generate Test Report
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.ADDRESS}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          script: |
            cd /home/ubuntu/repo/mlm
            ./gradlew test
            currentdate=$(date +"%d%m%Y-%H%M")
            origin="/home/ubuntu/repo/mlm/build/reports/tests/test"
            destination="/var/www/html/reports/$currentdate"
            mkdir "$destination/"
            cp -r "$origin" "$destination"
            systemctl restart nginx
      - name: Start MLM Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.ADDRESS}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          script: |
            cd /home/ubuntu/repo/mlm
            ./gradlew bootJar
            cp /home/ubuntu/repo/mlm/build/libs/mlm-1.3.0.jar /home/ubuntu/jar/
            cd /home/ubuntu/jar/
            rm app.jar
            mv mlm-1.3.0.jar app.jar
            systemctl stop app
            systemctl daemon-reload
            systemctl start app    
